<a href="https://colab.research.google.com/github/minnnnji/Machine_Learning/blob/master/KNN_%EB%8B%B9%EB%87%A8%EB%B3%91%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"minzzzzi","key":"74a980fb52033cf0ead89c84120a4a9c"}'}

In [ ]:
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle competitions download -c logistic-classification-diabetes-knn

train.csv: Skipping, found more recently modified local copy (use --force to force download)
test_data.csv: Skipping, found more recently modified local copy (use --force to force download)
submission_form.csv: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
import pandas as pd
import numpy as np


In [ ]:
train = pd.read_csv('train.csv',index_col=0)
test = pd.read_csv('test_data.csv',index_col = 0,usecols=[0,1,2,3,4,5,6,7,8])
submit = pd.read_csv('submission_form.csv')
test[:5]

0         1         2  ...         5         6         7
0 -0.882353  0.085427 -0.016393  ...  0.058122 -0.712212 -0.900000
1 -0.411765 -0.025126  0.245902  ...  0.061103 -0.743809  0.033333
2 -0.529412 -0.165829  0.409836  ... -0.126677 -0.795901 -0.566667
3 -0.882353  0.145729  0.081967  ...  0.135618 -0.819812  0.000000
4 -0.882353  0.497487  0.114754  ... -0.126677 -0.768574 -0.300000

[5 rows x 8 columns]

In [ ]:
tran[:5]

0         1         2         3  ...         5         6         7    8
0 -0.294118  0.487437  0.180328 -0.292929  ...  0.001490 -0.531170 -0.033333  0.0
1 -0.882353 -0.145729  0.081967 -0.414141  ... -0.207153 -0.766866 -0.666667  1.0
2 -0.058824  0.839196  0.049180  0.000000  ... -0.305514 -0.492741 -0.633333  0.0
3 -0.882353 -0.105528  0.081967 -0.535354  ... -0.162444 -0.923997  0.000000  1.0
4  0.000000  0.376884 -0.344262 -0.292929  ...  0.284650  0.887276 -0.600000  0.0

[5 rows x 9 columns]

In [ ]:
train = np.array(train)

(709, 9)

In [ ]:
test = np.array(test)
test.shape

(50, 8)

In [ ]:
x_train = train[:,0:8]
y_train = train[:,-1]

array([-0.882353 , -0.145729 ,  0.0819672, -0.414141 ,  0.       ,
       -0.207153 , -0.766866 , -0.666667 ])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3, p = 1)
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=1,
                     weights='uniform')

In [ ]:
y_train_pred = knn.predict(x_train)
test_pred = knn.predict(test)

print('misclassified training samples : %d' %(y_train!=y_train_pred).sum())

misclassified training samples : 105


In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train,y_train_pred))

0.8519040902679831


In [ ]:
test_pred

array([1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
       1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.])

In [ ]:
test_pred = test_pred.astype(int)


array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1])

In [ ]:
for i in range(len(test)):
  submit['Label'][i] = test_pred[i]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
submit['Label'] = submit['Label'].astype(int)

In [ ]:
submit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      50 non-null     int64
 1   Label   50 non-null     int64
dtypes: int64(2)
memory usage: 928.0 bytes


In [ ]:
submit.to_csv('submission.csv',index=False,header=True)

In [ ]:
!kaggle competitions submit -c logistic-classification-diabetes-knn -f submission.csv -m "Message"

100% 249/249 [00:02<00:00, 93.3B/s]
Successfully submitted to logistic classification : diabetes KNN