<a href="https://colab.research.google.com/github/minnnnji/Machine_Learning/blob/master/KNN_%EC%96%91%EB%B0%B0%EC%B6%94%EA%B0%80%EA%B2%A9%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"minzzzzi","key":"74a980fb52033cf0ead89c84120a4a9c"}'}

In [ ]:
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!pip uninstall -y kaggle
!pip install --upgrade pip
!pip install kaggle 

Uninstalling kaggle-1.5.8:
  Successfully uninstalled kaggle-1.5.8
     |████████████████████████████████| 1.5MB 2.8MB/s 
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
     |████████████████████████████████| 59 kB 1.6 MB/s 
  Created wheel for kaggle: filename=kaggle-1.5.8-py3-none-any.whl size=73274 sha256=3c972f824308532a2a353507b9d994e83e4437a56380af63a51ba19dbc496bab
  Stored in directory: /root/.cache/pip/wheels/cf/aa/f0/ed1179bbcd729b29d0dfda59826fb3b55f0a4a0c3f713c1c82
Successfully built kaggle


In [ ]:
!kaggle competitions download -c mlregression-cabbage-price

  0% 0.00/29.8k [00:00<?, ?B/s]
100% 29.8k/29.8k [00:00<00:00, 22.4MB/s]


In [ ]:
!unzip mlregression-cabbage-price.zip

Archive:  mlregression-cabbage-price.zip
  inflating: sample_submit.csv       
  inflating: test_cabbage_price.csv  
  inflating: train_cabbage_price.csv  


In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler


In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
x_train = train.loc[:,'avgTemp':'rainFall']
y_train = train.loc[:,'avgPrice']

In [ ]:
train = pd.read_csv('train_cabbage_price.csv')
test = pd.read_csv('test_cabbage_price.csv')
submit = pd.read_csv('sample_submit.csv')

train[:5]

year  avgTemp  minTemp  maxTemp  rainFall  avgPrice
0  20100101     -4.9    -11.0      0.9       0.0      2123
1  20100102     -3.1     -5.5      5.5       0.8      2123
2  20100103     -2.9     -6.9      1.4       0.0      2123
3  20100104     -1.8     -5.1      2.2       5.9      2020
4  20100105     -5.2     -8.7     -1.8       0.7      2060

In [ ]:
sc = StandardScaler()
mm = MinMaxScaler()

In [ ]:
x_train = train.loc[:,'avgTemp':'rainFall']
y_train = train.loc[:,'avgPrice']
x_train = np.array(x_train)
y_train = np.array(y_train)

In [ ]:
test = test.loc[:,'avgTemp':'rainFall']
test = np.array(test)
test[:5]

array([[ -3.2,  -9.1,   2.6,   2. ],
       [ -6. , -11.2,   0. ,   0.4],
       [ -9.9, -13.9,  -5.1,   0. ],
       [ -9. , -14.7,  -1.9,   0. ],
       [ -5.9, -13.1,   1. ,   0. ]])

In [ ]:
x_train = mm.fit_transform(x_train)
test = mm.fit_transform(test)

In [ ]:
x_train = sc.fit_transform(x_train)
test = sc.fit_transform(test)

In [ ]:
x_train

array([[-1.82680943, -1.88389429, -1.78377124, -0.40240956],
       [-1.64183875, -1.34361546, -1.31163108, -0.31000608],
       [-1.62128645, -1.48114098, -1.73245166, -0.40240956],
       ...,
       [-1.02526981, -1.00962491, -1.05503317, -0.40240956],
       [-1.02526981, -0.96050865, -1.14740842, -0.33310695],
       [-1.10747901, -0.99980166, -1.28083933, -0.35620782]])

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

regressor = KNeighborsRegressor(n_neighbors = 1000, weights = 'distance',p = 2)

regressor.fit(x_train,y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=1000, p=2,
                    weights='distance')

In [ ]:
pred = regressor.predict(test)
pred[:5]

array([2850.11574877, 2985.00310563, 2924.55666958, 2938.20023103,
       2937.99496259])

In [ ]:
for i in range(len(test)):
  submit['Expected'][i] = pred[i]

In [ ]:
submit[:5]

Id  Expected
0   0      2850
1   1      2985
2   2      2924
3   3      2938
4   4      2937

In [ ]:
submit.to_csv('submission.csv',index=False,header=True)

In [ ]:
!kaggle competitions submit -c mlregression-cabbage-price -f submission.csv -m "Message"

100% 6.33k/6.33k [00:00<00:00, 36.3kB/s]
Successfully submitted to [ML]Regression : Cabbage price